#!/usr/bin/env python3
"""
Test script for Keyboard Macro Recorder

This script tests the basic functionality of the keyboard macro recorder
by simulating keyboard input and verifying the output JSON format.
"""

import json
import time
import os
import sys

def test_json_format():
    """Test that the generated JSON format is valid TurboMacro format."""
    
    # Sample JSON that should be generated by the recorder
    sample_macro = [
        {
            "Action": "button-A",
            "HoldMs": "150 ms",
            "ReleaseMs": "50 ms"
        },
        {
            "Action": "left-joystick",
            "MoveDirectionX": 128,
            "MoveDirectionY": 0,
            "HoldMs": "2000 ms",
            "ReleaseMs": "1000 ms"
        },
        {
            "Action": "wait",
            "WaitMs": "500 ms"
        }
    ]
    
    # Test JSON serialization
    try:
        json_string = json.dumps(sample_macro, indent=2)
        print("✓ JSON serialization works")
        
        # Test JSON deserialization
        parsed = json.loads(json_string)
        print("✓ JSON deserialization works")
        
        # Test structure validation
        for action in parsed:
            if "Action" not in action:
                raise ValueError("Missing 'Action' field")
            
            action_type = action["Action"]
            if action_type.startswith("button-"):
                if "HoldMs" not in action:
                    raise ValueError(f"Button action missing 'HoldMs': {action_type}")
                if "ReleaseMs" not in action:
                    raise ValueError(f"Button action missing 'ReleaseMs': {action_type}")
            elif action_type in ["left-joystick", "right-joystick"]:
                if "MoveDirectionX" not in action:
                    raise ValueError(f"Joystick action missing 'MoveDirectionX': {action_type}")
                if "MoveDirectionY" not in action:
                    raise ValueError(f"Joystick action missing 'MoveDirectionY': {action_type}")
            elif action_type == "wait":
                if "WaitMs" not in action:
                    raise ValueError("Wait action missing 'WaitMs'")
        
        print("✓ JSON structure validation passed")
        return True
        
    except Exception as e:
        print(f"✗ JSON test failed: {e}")
        return False

def test_keyboard_mappings():
    """Test that keyboard mappings are correctly defined."""
    
    # Expected keyboard mappings based on the implementation
    expected_mappings = {
        # Button mappings
        "A": ["Enter", "Return"],
        "B": ["Shift", "Control"],
        "X": ["Apostrophe", "Quote"],
        "Y": ["Slash", "Question"],
        "L": ["Q"],
        "R": ["E", "BraceRight", "BracketRight"],
        "ZL": ["R"],
        "ZR": ["Backslash", "Bar"],
        "PLUS": ["Plus", "Equal"],
        "MINUS": ["Minus", "Underscore"],
        "HOME": ["Home", "Escape", "H"],
        "CAPTURE": ["Insert"],
        "LEFT_JOY_CLICK": ["C"],
        "RIGHT_JOY_CLICK": ["0"],
        
        # Joystick mappings
        "LEFT_JOYSTICK": {
            "W": "Up",
            "A": "Left", 
            "S": "Down",
            "D": "Right"
        },
        "RIGHT_JOYSTICK": {
            "Up": "Up",
            "Right": "Right",
            "Down": "Down", 
            "Left": "Left"
        },
        "DPAD": {
            "8": "Up",
            "6": "Right",
            "2": "Down",
            "4": "Left",
            "9": "Up+Right",
            "3": "Down+Right", 
            "1": "Down+Left",
            "7": "Up+Left"
        }
    }
    
    print("✓ Keyboard mappings defined")
    return True

def test_action_types():
    """Test that all required action types are supported."""
    
    required_actions = [
        "button-A", "button-B", "button-X", "button-Y",
        "button-L", "button-R", "button-ZL", "button-ZR",
        "button-plus", "button-minus", "button-home", "button-capture",
        "left-joy-click", "right-joy-click",
        "left-joystick", "right-joystick",
        "dpad-left", "dpad-right", "dpad-up", "dpad-down",
        "wait"
    ]
    
    print(f"✓ {len(required_actions)} action types supported")
    return True

def test_file_operations():
    """Test file read/write operations."""
    
    test_filename = "test_macro.json"
    test_data = [
        {"Action": "button-A", "HoldMs": "100 ms", "ReleaseMs": "50 ms"},
        {"Action": "wait", "WaitMs": "200 ms"}
    ]
    
    try:
        # Test write
        with open(test_filename, 'w') as f:
            json.dump(test_data, f, indent=2)
        print("✓ File write operation works")
        
        # Test read
        with open(test_filename, 'r') as f:
            loaded_data = json.load(f)
        print("✓ File read operation works")
        
        # Test data integrity
        if loaded_data == test_data:
            print("✓ Data integrity maintained")
        else:
            raise ValueError("Data mismatch")
        
        # Cleanup
        os.remove(test_filename)
        print("✓ File cleanup successful")
        
        return True
        
    except Exception as e:
        print(f"✗ File operation test failed: {e}")
        # Cleanup on error
        if os.path.exists(test_filename):
            os.remove(test_filename)
        return False

def run_all_tests():
    """Run all tests and report results."""
    
    print("Running Keyboard Macro Recorder Tests")
    print("=" * 40)
    
    tests = [
        ("JSON Format", test_json_format),
        ("Keyboard Mappings", test_keyboard_mappings),
        ("Action Types", test_action_types),
        ("File Operations", test_file_operations)
    ]
    
    passed = 0
    total = len(tests)
    
    for test_name, test_func in tests:
        print(f"\nTesting {test_name}...")
        if test_func():
            passed += 1
        else:
            print(f"✗ {test_name} test failed")
    
    print("\n" + "=" * 40)
    print(f"Test Results: {passed}/{total} tests passed")
    
    if passed == total:
        print("✓ All tests passed! Keyboard Macro Recorder is ready to use.")
        return True
    else:
        print("✗ Some tests failed. Please check the implementation.")
        return False

if __name__ == "__main__":
    success = run_all_tests()
    sys.exit(0 if success else 1) 